import type { ChapterDefinition } from '../quests/types';

/**
 * The chapter list. Phase 0 ships the practice quest (chapter 0) as a
 * complete, playable definition, plus the seven lesson chapters as
 * 'coming-soon' outlines so the journal's chapter map, unlock order and
 * save format are real from the start. Each later phase fills in one
 * outline (steps, conversations, items, minigame) and flips it to
 * 'playable'. The hub itself does not change.
 */

const comingSoonCarver = (n: number) => ({
  opening: `carver_ch${n}_opening`,
  waiting: `carver_ch${n}_waiting`,
  closing: `carver_ch${n}_closing`,
  after: `carver_ch${n}_after`,
});

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: 'practice',
    number: 0,
    title: 'Seeds for the Windowsill',
    subtitle: 'Practice quest',
    status: 'playable',
    assignment: "Carver asked you to collect his seed packet from Mae Porter at the Seed & Mail and bring it to him.",
    whyItMatters: 'Carver wants you to practise looking closely. Noticing details is where every investigation begins.',
    carver: {
      opening: 'carver_practice_opening',
      waiting: 'carver_practice_waiting',
      closing: 'carver_practice_closing',
      after: 'carver_practice_after',
    },
    steps: [
      {
        id: 'get_seeds',
        kind: 'talk',
        npcId: 'mae',
        text: 'Get the seed packet from Mae at the Seed & Mail',
        lead: 'Mae Porter is keeping a packet of seeds for Carver at the Seed & Mail, east of the town square.',
        conversation: 'mae_practice_give',
        after: 'mae_practice_after',
        grants: ['seed_packet'],
      },
    ],
    requiredItems: ['seed_packet'],
    itemUses: [{ itemId: 'seed_packet', usedIn: 'carver', description: 'Show Carver what you noticed, then give him the seeds to plant.' }],
    rewards: { xp: 50, seeds: 10, unlock: 'Seed pot on your windowsill' },
    objectives: ['observe'],
  },
  {
    id: 'ch1',
    number: 1,
    title: 'A Seed Is Planted',
    subtitle: 'Curiosity Collector',
    status: 'coming-soon',
    assignment: 'Investigate what the garden is telling us.',
    whyItMatters: 'Careful observations are the start of all science.',
    carver: comingSoonCarver(1),
    steps: [],
    requiredItems: ['field_notebook', 'magnifying_lens'],
    itemUses: [],
    rewards: { xp: 150, seeds: 20 },
    objectives: ['observe'],
    analogActivity: { title: 'Nature observation card', description: 'Go outside and record three things you can see, hear or touch.' },
  },
  {
    id: 'ch2',
    number: 2,
    title: 'Science Against the Odds',
    subtitle: 'Choose the Path',
    status: 'coming-soon',
    assignment: 'Reconstruct how a curious learner found a path to science.',
    whyItMatters: "Carver's journey shows how learning and support helped him become a scientist.",
    carver: comingSoonCarver(2),
    steps: [],
    requiredItems: ['school_record', 'botanical_sketch'],
    itemUses: [],
    rewards: { xp: 150, seeds: 20 },
    objectives: ['journey'],
    analogActivity: { title: 'Journey timeline and reflection', description: 'Draw a timeline of something you learned and who helped you.' },
  },
  {
    id: 'ch3',
    number: 3,
    title: 'The Soil Speaks',
    subtitle: 'Virtual Soil Lab',
    status: 'coming-soon',
    assignment: 'Find a better plan for tired farmland.',
    whyItMatters: 'Healthy soil feeds families year after year.',
    carver: comingSoonCarver(3),
    steps: [],
    requiredItems: ['soil_samples', 'crop_cards'],
    itemUses: [],
    rewards: { xp: 150, seeds: 20 },
    objectives: ['soil'],
    analogActivity: { title: 'Crop-rotation planner', description: 'Plan four seasons of planting on paper or with cups of soil.' },
  },
  {
    id: 'ch4',
    number: 4,
    title: "The Peanut Isn't Just a Peanut",
    subtitle: "Inventor's Workshop",
    status: 'coming-soon',
    assignment: 'Find a useful new purpose for a crop.',
    whyItMatters: 'Testing ideas against a real need turns a crop into a solution.',
    carver: comingSoonCarver(4),
    steps: [],
    requiredItems: ['need_card', 'materials_kit'],
    itemUses: [],
    rewards: { xp: 150, seeds: 25 },
    objectives: ['invent'],
    analogActivity: { title: 'Invention sketch', description: 'Sketch an invention using things you can find at home.' },
  },
  {
    id: 'ch5',
    number: 5,
    title: 'Science for the People',
    subtitle: 'Farm Helper',
    status: 'coming-soon',
    assignment: 'Help neighbors with different growing problems.',
    whyItMatters: 'Science matters most when it helps real people.',
    carver: comingSoonCarver(5),
    steps: [],
    requiredItems: ['farm_report_a', 'farm_report_b', 'resource_map'],
    itemUses: [],
    rewards: { xp: 150, seeds: 25 },
    objectives: ['help'],
    analogActivity: { title: 'Growing-need interview', description: 'Ask someone about a problem with growing food or plants.' },
  },
  {
    id: 'ch6',
    number: 6,
    title: "A Scientist's Method",
    subtitle: 'Design Your Own Experiment',
    status: 'coming-soon',
    assignment: 'Design a fair test for an unanswered question.',
    whyItMatters: 'Changing one thing at a time lets data tell the truth.',
    carver: comingSoonCarver(6),
    steps: [],
    requiredItems: ['measuring_tool', 'trial_seeds'],
    itemUses: [],
    rewards: { xp: 200, seeds: 30 },
    objectives: ['method'],
    analogActivity: { title: 'One-variable plant experiment', description: 'Plan a safe seed test that changes just one thing.' },
  },
  {
    id: 'ch7',
    number: 7,
    title: 'Your Turn to Plant the Seeds',
    subtitle: 'My Carver Project',
    status: 'coming-soon',
    assignment: 'Use what you learned to help your own community.',
    whyItMatters: 'Now you are the scientist and inventor.',
    carver: comingSoonCarver(7),
    steps: [],
    requiredItems: ['need_cards', 'prototype_kit'],
    itemUses: [],
    rewards: { xp: 250, seeds: 40 },
    objectives: ['capstone'],
    analogActivity: { title: 'Invention poster and test log', description: 'Make a poster of your invention and how you would test it.' },
  },
];
