import type { ChapterDefinition } from '../quests/types';

/**
 * The chapter list. Phase 0 ships the practice quest (chapter 0) as a
 * complete, playable definition, plus the seven lesson chapters as
 * 'coming-soon' outlines so the journal's chapter map, unlock order and
 * save format are real from the start. Each later phase fills in one
 * outline (steps, conversations, items, minigame) and flips it to
 * 'playable'. The hub itself does not change.
 */

const comingSoonCarver = (n: number) => ({
  opening: `carver_ch${n}_opening`,
  waiting: `carver_ch${n}_waiting`,
  closing: `carver_ch${n}_closing`,
  after: `carver_ch${n}_after`,
});

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: 'practice',
    number: 0,
    title: 'Seeds for the Windowsill',
    subtitle: 'Practice quest',
    status: 'playable',
    assignment: "Carver asked you to collect his seed packet from Mae Porter at the Seed & Mail and bring it to him.",
    whyItMatters: 'Carver wants you to practise looking closely. Noticing details is where every investigation begins.',
    carver: {
      opening: 'carver_practice_opening',
      waiting: 'carver_practice_waiting',
      closing: 'carver_practice_closing',
      after: 'carver_practice_after',
    },
    steps: [
      {
        id: 'get_seeds',
        kind: 'talk',
        npcId: 'mae',
        text: 'Get the seed packet from Mae at the Seed & Mail',
        lead: 'Mae Porter is keeping a packet of seeds for Carver at the Seed & Mail, east of the town square.',
        conversation: 'mae_practice_give',
        after: 'mae_practice_after',
        grants: ['seed_packet'],
      },
    ],
    requiredItems: ['seed_packet'],
    itemUses: [{ itemId: 'seed_packet', usedIn: 'carver', description: 'Show Carver what you noticed, then give him the seeds to plant.' }],
    rewards: { xp: 50, seeds: 10, unlock: 'Seed pot on your windowsill' },
    reflection: 'You practised telling an observation (something anyone can check right now) from a guess or an opinion.',
    objectives: ['observe'],
  },
  {
    id: 'ch1',
    number: 1,
    title: 'A Seed Is Planted',
    subtitle: 'Curiosity Collector',
    status: 'playable',
    assignment: 'Investigate what the community garden is telling us. Get tools from Hattie and Theo, look closely, and write down only what you can really see.',
    whyItMatters: 'Careful observations are the start of all science. Carver learned about plants by watching them closely as a boy.',
    carver: {
      opening: 'carver_ch1_opening',
      waiting: 'carver_ch1_waiting',
      closing: 'carver_ch1_closing',
      after: 'carver_ch1_after',
    },
    steps: [
      {
        id: 'get_notebook',
        kind: 'talk',
        npcId: 'hattie',
        text: 'Get the field notebook from Hattie at the garden gate',
        lead: 'Hattie Bell, the gardener, keeps a field notebook for Carver. She is by the community garden gate.',
        conversation: 'hattie_ch1_give',
        after: 'hattie_ch1_after',
        grants: ['field_notebook'],
      },
      {
        id: 'get_lens',
        kind: 'talk',
        npcId: 'theo',
        text: 'Borrow the magnifying lens from Theo by the pond',
        lead: 'Theo, a young naturalist, always carries a magnifying lens. He is on the east side of the pond.',
        conversation: 'theo_ch1_give',
        after: 'theo_ch1_after',
        grants: ['magnifying_lens'],
      },
      {
        id: 'observe_sort',
        kind: 'minigame',
        minigameId: 'curiosity-collector',
        text: 'Inspect the garden spots, then sort your notes at the potting bench',
        placeId: 'garden',
        uses: ['field_notebook', 'magnifying_lens'],
      },
    ],
    requiredItems: ['field_notebook', 'magnifying_lens'],
    itemUses: [
      { itemId: 'magnifying_lens', usedIn: 'minigame:curiosity-collector', description: 'Look closely at each garden spot to find small details.' },
      { itemId: 'field_notebook', usedIn: 'minigame:curiosity-collector', description: 'Write down specific observations, then sort them from guesses.' },
    ],
    rewards: { xp: 150, seeds: 20, unlock: 'Nature Observation Card, and Chapter 2' },
    reflection:
      'You used a lens to find small details, wrote specific observations (with numbers, colors and sizes), and sorted them from guesses. That is how every investigation starts.',
    objectives: ['observe'],
    analogActivity: {
      title: 'Nature observation card',
      description: 'Go outside and record one thing you see, one you hear and one you touch. Write what is there, not what you think happened.',
    },
    loadRuntime: () => import('../chapters/ch1/runtime'),
  },
  {
    id: 'ch2',
    number: 2,
    title: 'Science Against the Odds',
    subtitle: 'Choose the Path',
    status: 'playable',
    assignment:
      "Put Carver's school years back in order using the schoolhouse displays, Ms. Nelson's records and Ada's clue. Then name one thing that stood in his way and one person who helped.",
    whyItMatters: "Carver's journey shows how learning, and the people who helped him, made him a scientist, even when unfair rules closed doors.",
    carver: {
      opening: 'carver_ch2_opening',
      waiting: 'carver_ch2_waiting',
      closing: 'carver_ch2_closing',
      after: 'carver_ch2_after',
    },
    steps: [
      {
        id: 'get_record',
        kind: 'talk',
        npcId: 'ruth',
        text: 'Get the school records from Ms. Nelson by the schoolhouse',
        lead: 'Ms. Ruth Nelson, the teacher, has a folder of records about Carver\'s schooling. She is outside the schoolhouse.',
        conversation: 'ruth_ch2_give',
        after: 'ruth_ch2_after',
        grants: ['school_record'],
      },
      {
        id: 'get_sketch',
        kind: 'talk',
        npcId: 'ada',
        text: 'Visit Ada, the young artist in the town square',
        lead: 'Ada, a young artist, is sketching in the town square. She knows about Carver and art.',
        conversation: 'ada_ch2_give',
        after: 'ada_ch2_after',
        grants: ['botanical_sketch'],
      },
      {
        id: 'build_timeline',
        kind: 'minigame',
        minigameId: 'journey-timeline',
        text: 'Visit the displays in the schoolhouse, then build the timeline on the chalkboard',
        placeId: 'school',
        uses: ['school_record', 'botanical_sketch'],
      },
    ],
    requiredItems: ['school_record', 'botanical_sketch'],
    itemUses: [
      { itemId: 'school_record', usedIn: 'minigame:journey-timeline', description: 'Dates for the timeline cards.' },
      { itemId: 'botanical_sketch', usedIn: 'minigame:journey-timeline', description: 'A clue: Carver studied art before plants.' },
    ],
    rewards: { xp: 150, seeds: 20, unlock: 'Journey Card, and Chapter 3' },
    objectives: ['journey'],
    analogActivity: { title: 'Journey timeline and reflection', description: 'Draw a timeline of something you learned and who helped you.' },
    reflection:
      "You put the stages of Carver's education in order, named racism as an unfair barrier, and named people who supported him. Learning gave him tools to help others.",
    loadRuntime: () => import('../chapters/ch2/runtime'),
  },
  {
    id: 'ch3',
    number: 3,
    title: 'The Soil Speaks',
    subtitle: 'Virtual Soil Lab',
    status: 'playable',
    assignment:
      "Find out why Mr. Hill's west plot is worn out. Compare his two plots up close, test planting plans for four seasons, and bring Carver a plan that still grows cotton and helps the soil.",
    whyItMatters: 'Healthy soil feeds families year after year. Carver taught farmers to take turns with crops so tired fields could recover.',
    carver: {
      opening: 'carver_ch3_opening',
      waiting: 'carver_ch3_waiting',
      closing: 'carver_ch3_closing',
      after: 'carver_ch3_after',
    },
    steps: [
      {
        id: 'get_samples',
        kind: 'talk',
        npcId: 'amos',
        text: 'Get soil samples and the crop history from Mr. Hill by the farm gate',
        lead: 'Mr. Amos Hill, the farmer, has soil samples and a record of what he planted. He is by the Hilltop Farm gate, north of the road.',
        conversation: 'amos_ch3_give',
        after: 'amos_ch3_after',
        grants: ['soil_samples', 'crop_history'],
      },
      {
        id: 'get_cards',
        kind: 'talk',
        npcId: 'mae',
        text: 'Get crop cards from Mae at the Seed & Mail',
        lead: 'Mae Porter keeps crop cards for the crops that grow around here. She is at the Seed & Mail stall.',
        conversation: 'mae_ch3_give',
        after: 'mae_ch3_after',
        grants: ['crop_cards'],
      },
      {
        id: 'soil_lab',
        kind: 'minigame',
        minigameId: 'soil-lab',
        text: 'Look at both plots up close, then test plans at the bench in Hilltop Farm',
        placeId: 'farm',
        uses: ['soil_samples', 'crop_history', 'crop_cards'],
      },
    ],
    requiredItems: ['soil_samples', 'crop_history', 'crop_cards'],
    itemUses: [
      { itemId: 'soil_samples', usedIn: 'minigame:soil-lab', description: 'Magnified views of each plot\'s soil.' },
      { itemId: 'crop_history', usedIn: 'minigame:soil-lab', description: 'What each plot grew before.' },
      { itemId: 'crop_cards', usedIn: 'minigame:soil-lab', description: 'The crops to plan with, legumes marked.' },
    ],
    rewards: { xp: 150, seeds: 20, unlock: 'Crop-Rotation Planner, and Chapter 4' },
    objectives: ['soil'],
    analogActivity: { title: 'Crop-rotation planner', description: 'Plan four seasons of planting on paper or with cups of soil.' },
    reflection:
      'You compared tired soil with healthy soil, tested planting plans, and found that cotton every year wears soil out, while taking turns with legumes slowly helps it recover.',
    loadRuntime: () => import('../chapters/ch3/runtime'),
  },
  {
    id: 'ch4',
    number: 4,
    title: "The Peanut Isn't Just a Peanut",
    subtitle: "Inventor's Workshop",
    status: 'coming-soon',
    assignment: 'Find a useful new purpose for a crop.',
    whyItMatters: 'Testing ideas against a real need turns a crop into a solution.',
    carver: comingSoonCarver(4),
    steps: [],
    requiredItems: ['need_card', 'materials_kit'],
    itemUses: [],
    rewards: { xp: 150, seeds: 25 },
    objectives: ['invent'],
    analogActivity: { title: 'Invention sketch', description: 'Sketch an invention using things you can find at home.' },
  },
  {
    id: 'ch5',
    number: 5,
    title: 'Science for the People',
    subtitle: 'Farm Helper',
    status: 'coming-soon',
    assignment: 'Help neighbors with different growing problems.',
    whyItMatters: 'Science matters most when it helps real people.',
    carver: comingSoonCarver(5),
    steps: [],
    requiredItems: ['farm_report_a', 'farm_report_b', 'resource_map'],
    itemUses: [],
    rewards: { xp: 150, seeds: 25 },
    objectives: ['help'],
    analogActivity: { title: 'Growing-need interview', description: 'Ask someone about a problem with growing food or plants.' },
  },
  {
    id: 'ch6',
    number: 6,
    title: "A Scientist's Method",
    subtitle: 'Design Your Own Experiment',
    status: 'coming-soon',
    assignment: 'Design a fair test for an unanswered question.',
    whyItMatters: 'Changing one thing at a time lets data tell the truth.',
    carver: comingSoonCarver(6),
    steps: [],
    requiredItems: ['measuring_tool', 'trial_seeds'],
    itemUses: [],
    rewards: { xp: 200, seeds: 30 },
    objectives: ['method'],
    analogActivity: { title: 'One-variable plant experiment', description: 'Plan a safe seed test that changes just one thing.' },
  },
  {
    id: 'ch7',
    number: 7,
    title: 'Your Turn to Plant the Seeds',
    subtitle: 'My Carver Project',
    status: 'coming-soon',
    assignment: 'Use what you learned to help your own community.',
    whyItMatters: 'Now you are the scientist and inventor.',
    carver: comingSoonCarver(7),
    steps: [],
    requiredItems: ['need_cards', 'prototype_kit'],
    itemUses: [],
    rewards: { xp: 250, seeds: 40 },
    objectives: ['capstone'],
    analogActivity: { title: 'Invention poster and test log', description: 'Make a poster of your invention and how you would test it.' },
  },
];
